---
title: "Project 0 - Introductory Project"
subtitle: "Course DS 250"
author: "Satchel Murphy"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
    
---

```{python}
#| label: libraries
#| include: false
import pandas as pd
import altair as alt
import numpy as np

from IPython.display import Markdown
from IPython.display import display
from tabulate import tabulate
```


## Elevator pitch

_paste your elevator pitch here_

```{python}
#| label: project data
#| code-summary: Read and format project data
# Include and execute your code here

```

__Highlight the grand questions__

## GRAND QUESTION 1

__Finish the readings and be prepared with any questions to get your environment working smoothly (class for on-campus and Slack for online)__

_type your results and analysis here_

```{python}
#| label: GQ1
#| code-summary: Read and format data
# Include and execute your code here
url="https://github.com/byuidatascience/data4python4ds/raw/master/data-raw/mpg/mpg.csv"
mpg=pd.read_csv(url)

```

_include figures in chunks and discuss your findings in the figure._


## GRAND QUESTION 2

__Finish the readings and be prepared with any questions to get your environment working smoothly (class for on-campus and Slack for online)__

_type your results and analysis here_



_include figures in chunks and discuss your findings in the figure._

```{python}
#| label: GQ2 chart
#| code-summary: plot example
#| fig-cap: "My useless chart"
#| fig-align: center
# Include and execute your code here
chart = alt.Chart(mpg).mark_circle().encode(
            x='displ', 
            y='hwy'
    )

chart
```




## GRAND QUESTION 3

__Your final report should also include the markdown table created from the following (assuming you have mpg from question 2).__

_type your results and analysis here_



_include figures in chunks and discuss your findings in the figure._




```{python}
#| label: GQ3 table
#| code-summary: table example
#| tbl-cap: "Not much of a table"
#| tbl-cap-location: top
# Include and execute your code here
(mpg
    .head(5)
    .filter(["manufacturer", "model","year", "hwy"]))

```



## APPENDIX A (Additional Python Code)

```python
#paste other your code from your python file (.py) here
```
