---
title: "Project 1 - What Is A Name? "
subtitle: "Course DS 250"
author: "Satchel Murphy"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
    
---

```{python}
#| label: libraries
#| include: false
import pandas as pd
import altair as alt
import numpy as np

from IPython.display import Markdown
from IPython.display import display
from tabulate import tabulate
```


## Elevator pitch

_paste your elevator pitch here_

```{python}
#| label: project data
#| code-summary: Read and format project data
# Include and execute your code here
dat = pd.read_csv("https://github.com/byuidatascience/data4names/raw/master/data-raw/names_year/names_year.csv")
```


## GRAND QUESTION 1

How does your name at your birth year compare to its use historically?

My name that was given to me at birth is Joshua. It seemed to be a very common name at the time as I had a cousin the same age as me also named Joshua. I grew up knowing several other peers with my name. As I can see here in the chart, I was correct in feeling that it was a common name. There were about 25,000 babies named Joshua when I was born.

```{python}
#| label: GQ1
#| code-summary: Read and format data

import pandas as pd
import altair as alt

url="https://raw.githubusercontent.com/byuidatascience/data4names/master/data-raw/names_year/names_year.csv"
NameData= pd.read_csv(url)

MyName = NameData.query("name == 'Joshua'")
```


```{python}
#| label: GQ1 chart
#| code-summary: My Name over the Years
#| fig-cap: ""
#| fig-align: center

title = "My Name Was Popular When I Was Born"
NameGraph = alt.Chart(MyName, title=title).mark_line().encode(
    x=alt.X("year", title="Year", axis=alt.Axis(format="d")),
    y=alt.Y("Total", title="Babies Named Joshua")
)

YearData = pd.DataFrame({"year": [1997]})

YearChart = alt.Chart(YearData).mark_rule(color="red").encode(
    x="year"
)

NameGraph+YearChart

```


```{python}
#| label: GQ1 table
#| code-summary: table example
#| tbl-cap: ""
#| tbl-cap-location: top
# Include and execute your code here
MyName

```


## GRAND QUESTION 2

If you talked to someone named Brittany on the phone, what is your guess of his or her age? What ages would you not guess?

Talking to someone named Brittany on the phone I would assume that they were in between 25 and 35. The year that Brittany was most popular was the year 1990, around 32500 people were named Brittany that year.

```{python}
#| label: GQ2
#| code-summary: The name Brittany over the years
# Include and execute your code here
import pandas as pd
import altair as alt

url="https://raw.githubusercontent.com/byuidatascience/data4names/master/data-raw/names_year/names_year.csv"
NameData= pd.read_csv(url)

Brittany = NameData.query("name == 'Brittany'")

```



```{python}
#| label: GQ2 chart
#| code-summary: The name Brittany over the years
#| fig-cap: ""
#| fig-align: center
# Include and execute your code here

titleBrit = "Years of Babies Named Brittany"

BritGraph= alt.Chart(Brittany, title=titleBrit).mark_line().encode(
    x=alt.X("year", title="Year", axis=alt.Axis(format="d")),
    y=alt.Y("Total", title="Babies Named Brittany")
)

BritGraph

```


```{python}
#| label: GQ2 table
#| code-summary: table example
#| tbl-cap: ""
#| tbl-cap-location: top
# Include and execute your code here
Brittany
```


## GRAND QUESTION 3

Mary, Martha, Peter, and Paul are all Christian names. From 1920 - 2000, compare the name usage of each of the four names. What trends do you notice?

Mary has been an extremely popular name for a long time. From 1920 to 1960, Mary was averaging close to 40,000 each year. The second most popular name of these four names was Paul. Paul became popular in 1955 where it got up to 25,000. However, the biblical names lost popularity in the 1980s and have declined ever since. 

```{python}
#| label: GQ3
#| code-summary: Read and format data
# Include and execute your code here
titleBib= "4 Famous Biblical Names in Recent Years"

BibName = NameData.query("name == 'Mary' | name == 'Peter' | name == 'Paul' | name == 'Martha'")
BibName

```


```{python}
#| label: GQ3 chart
#| code-summary: Four Popular Biblical names over the years
#| fig-cap: ""
#| fig-align: center
# Include and execute your code here
BibGraph = alt.Chart(BibName , title=titleBib).mark_line().encode(
    x=alt.X("year", title="Year", axis=alt.Axis(format="d")),
    y=alt.Y("Total", title="Babies Named "),
    color="name"
)

BibGraph
```




## GRAND QUESTION 4

Think of a unique name from a famous movie. Plot the usage of that name and see how changes line up with the movie release. Does it look like the movie had an effect on usage?

```{python}
#| label: GQ4
#| code-summary: Read and format data
# Include and execute your code here
BatName = NameData.query("name == 'Christian'")

Battitle = "Christian and Batman Movies"
```


```{python}
#| label: GQ4 chart
#| code-summary: Christain Bale's Influence
#| fig-cap: ""
#| fig-align: center
# Include and execute your code here
BatNameGraph = alt.Chart(BatName, title=Battitle).mark_line().encode(
    x=alt.X("year", title="Year", axis=alt.Axis(format="d")),
    y=alt.Y("Total", title="Babies Named Christian")
)

YearData = pd.DataFrame({"year": [2005]})

YearChart = alt.Chart(YearData).mark_rule(color="red").encode(
    x="year"
)

BatNameGraph+YearChart
```

We can see here that Christian Bale may have had an influence on the name's popularity for a little bit, but then it may have felt like it was popularized and parents no longer wanted to copy other parents and strayed from the name Christian. After the movie released, there is a pretty sharp decline in babies given that name.


## APPENDIX A (Additional Python Code)

```python
#paste other your code from your python file (.py) here
```

